// ─── Outlet types ─────────────────────────────────────────────────────────────
// Static, factual data — never leave this to an AI.
// Imported directly by the client component so it's always correct regardless
// of API responses or sessionStorage cache.

export const OUTLET_LOOKUP: Record<string, string> = {
  // ── Type A/B (US-compatible) ──────────────────────────────────────────────
  "United States":            "US-compatible (Type A/B · 120V · 60Hz)",
  "Canada":                   "US-compatible (Type A/B · 120V · 60Hz)",
  "Mexico":                   "US-compatible (Type A/B · 127V · 60Hz)",
  "Taiwan":                   "US-compatible (Type A/B · 110V · 60Hz)",
  "Japan":                    "US-compatible (Type A · 100V · 50/60Hz) — US plugs fit, but voltage is lower",
  "Colombia":                 "US-compatible (Type A/B · 110V · 60Hz)",
  "Venezuela":                "US-compatible (Type A/B · 120V · 60Hz)",
  "Ecuador":                  "US-compatible (Type A/B · 120V · 60Hz)",
  "El Salvador":              "US-compatible (Type A/B · 120V · 60Hz)",
  "Guatemala":                "US-compatible (Type A/B · 120V · 60Hz)",
  "Honduras":                 "US-compatible (Type A/B · 120V · 60Hz)",
  "Nicaragua":                "US-compatible (Type A/B · 120V · 60Hz)",
  "Costa Rica":               "US-compatible (Type A/B · 120V · 60Hz)",
  "Panama":                   "US-compatible (Type A/B · 120V · 60Hz)",
  "Cuba":                     "US-compatible (Type A/B · 110V · 60Hz)",
  "Dominican Republic":       "US-compatible (Type A/B · 110V · 60Hz)",
  "Haiti":                    "US-compatible (Type A/B · 110V · 60Hz)",
  "Jamaica":                  "US-compatible (Type A/B · 110V · 50Hz)",
  "Philippines":              "US-compatible (Type A/B · 220V · 60Hz) — US plugs fit but voltage is higher",
  "Trinidad and Tobago":      "US-compatible (Type A/B · 115V · 60Hz)",
  "Barbados":                 "US-compatible (Type A/B · 115V · 50Hz)",

  // ── Type G (UK-compatible) ────────────────────────────────────────────────
  "United Kingdom":           "UK-compatible (Type G · 230V · 50Hz)",
  "Ireland":                  "UK-compatible (Type G · 230V · 50Hz)",
  "Malta":                    "UK-compatible (Type G · 230V · 50Hz)",
  "Cyprus":                   "UK-compatible (Type G · 230V · 50Hz)",
  "Singapore":                "UK-compatible (Type G · 230V · 50Hz)",
  "Malaysia":                 "UK-compatible (Type G · 230V · 50Hz)",
  "Hong Kong":                "UK-compatible (Type G · 230V · 50Hz)",
  "United Arab Emirates":     "UK-compatible (Type G · 230V · 50Hz)",
  "Qatar":                    "UK-compatible (Type G · 230V · 50Hz)",
  "Bahrain":                  "UK-compatible (Type G · 230V · 50Hz)",
  "Kuwait":                   "UK-compatible (Type G · 230V · 50Hz)",
  "Kenya":                    "UK-compatible (Type G · 230V · 50Hz)",
  "Uganda":                   "UK-compatible (Type G · 230V · 50Hz)",
  "Tanzania":                 "UK-compatible (Type G · 230V · 50Hz)",
  "Rwanda":                   "UK-compatible (Type G · 230V · 50Hz)",
  "Nigeria":                  "UK-compatible (Type G · 230V · 50Hz)",
  "Ghana":                    "UK-compatible (Type G · 230V · 50Hz)",
  "Pakistan":                 "UK-compatible (Type G · 230V · 50Hz)",
  "Sri Lanka":                "UK-compatible (Type G · 230V · 50Hz)",
  "Maldives":                 "UK-compatible (Type G · 230V · 50Hz)",
  "Brunei":                   "UK-compatible (Type G · 230V · 50Hz)",
  "Zambia":                   "UK-compatible (Type G · 230V · 50Hz)",
  "Zimbabwe":                 "UK-compatible (Type G · 230V · 50Hz)",
  "Botswana":                 "UK-compatible (Type G/M · 230V · 50Hz)",

  // ── Type I (AU/NZ-compatible) ─────────────────────────────────────────────
  "Australia":                "AU/NZ-compatible (Type I · 230V · 50Hz)",
  "New Zealand":              "AU/NZ-compatible (Type I · 230V · 50Hz)",
  "Papua New Guinea":         "AU/NZ-compatible (Type I · 240V · 50Hz)",
  "Argentina":                "AU/NZ-compatible (Type I · 220V · 50Hz)",

  // ── China ─────────────────────────────────────────────────────────────────
  "China":                    "Multi-type (Type A/I · 220V · 50Hz) — sockets often accept US-style flat and AU-style angled prongs",

  // ── EU-compatible (Type C/E/F) ────────────────────────────────────────────
  "France":                   "EU-compatible (Type C/E · 230V · 50Hz)",
  "Germany":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Spain":                    "EU-compatible (Type C/F · 230V · 50Hz)",
  "Italy":                    "EU-compatible (Type C/F/L · 230V · 50Hz)",
  "Portugal":                 "EU-compatible (Type C/F · 230V · 50Hz)",
  "Netherlands":              "EU-compatible (Type C/F · 230V · 50Hz)",
  "Belgium":                  "EU-compatible (Type C/E · 230V · 50Hz)",
  "Switzerland":              "EU-compatible (Type C/J · 230V · 50Hz)",
  "Austria":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Greece":                   "EU-compatible (Type C/F · 230V · 50Hz)",
  "Poland":                   "EU-compatible (Type C/E · 230V · 50Hz)",
  "Czech Republic":           "EU-compatible (Type C/E · 230V · 50Hz)",
  "Hungary":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Romania":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Sweden":                   "EU-compatible (Type C/F · 230V · 50Hz)",
  "Norway":                   "EU-compatible (Type C/F · 230V · 50Hz)",
  "Denmark":                  "EU-compatible (Type C/K · 230V · 50Hz)",
  "Finland":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Croatia":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Serbia":                   "EU-compatible (Type C/F · 230V · 50Hz)",
  "Albania":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "North Macedonia":          "EU-compatible (Type C/F · 230V · 50Hz)",
  "Bosnia and Herzegovina":   "EU-compatible (Type C/F · 230V · 50Hz)",
  "Montenegro":               "EU-compatible (Type C/F · 230V · 50Hz)",
  "Slovenia":                 "EU-compatible (Type C/F · 230V · 50Hz)",
  "Slovakia":                 "EU-compatible (Type C/E · 230V · 50Hz)",
  "Bulgaria":                 "EU-compatible (Type C/F · 230V · 50Hz)",
  "Lithuania":                "EU-compatible (Type C/F · 230V · 50Hz)",
  "Latvia":                   "EU-compatible (Type C/F · 230V · 50Hz)",
  "Estonia":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Turkey":                   "EU-compatible (Type C/F · 230V · 50Hz)",
  "Russia":                   "EU-compatible (Type C/F · 230V · 50Hz)",
  "Ukraine":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Morocco":                  "EU-compatible (Type C/E · 220V · 50Hz)",
  "Tunisia":                  "EU-compatible (Type C/E · 230V · 50Hz)",
  "Algeria":                  "EU-compatible (Type C/F · 230V · 50Hz)",
  "Egypt":                    "EU-compatible (Type C/F · 220V · 50Hz)",
  "Israel":                   "EU-compatible (Type C/H · 230V · 50Hz)",
  "Jordan":                   "EU-compatible (Type C/D/F/G · 230V · 50Hz)",
  "Lebanon":                  "EU-compatible (Type C/D · 230V · 50Hz)",
  "Brazil":                   "EU-compatible (Type N · 127/220V · 60Hz) — voltage varies by region",
  "Peru":                     "EU-compatible (Type C/A · 220V · 60Hz)",
  "Chile":                    "EU-compatible (Type C/L · 220V · 50Hz)",
  "Bolivia":                  "EU-compatible (Type A/C · 220V · 50Hz)",
  "Paraguay":                 "EU-compatible (Type C · 220V · 50Hz)",
  "Uruguay":                  "EU-compatible (Type C/F/I · 220V · 50Hz)",
  "South Africa":             "Type M + EU (Type C/M/N · 230V · 50Hz) — bring an adapter",
  "Ethiopia":                 "EU-compatible (Type C/F/L · 220V · 50Hz)",
  "Mozambique":               "EU-compatible (Type C/F/M · 220V · 50Hz)",
  "Namibia":                  "Type M (220V · 50Hz) — same large round 3-pin as South Africa",
  "Senegal":                  "EU-compatible (Type C/D/E · 230V · 50Hz)",
  "Cameroon":                 "EU-compatible (Type C/E · 220V · 50Hz)",
  "Democratic Republic of Congo": "EU-compatible (Type C · 220V · 50Hz)",
  "Iran":                     "EU-compatible (Type C/F · 220V · 50Hz)",
  "South Korea":              "EU-compatible (Type C/F · 220V · 60Hz)",
  "Mongolia":                 "EU-compatible (Type C/E · 220V · 50Hz)",
  "Kazakhstan":               "EU-compatible (Type C/F · 220V · 50Hz)",
  "Georgia":                  "EU-compatible (Type C/F · 220V · 50Hz)",
  "Armenia":                  "EU-compatible (Type C/F · 220V · 50Hz)",
  "Azerbaijan":               "EU-compatible (Type C/F · 220V · 50Hz)",
  "Uzbekistan":               "EU-compatible (Type C/I · 220V · 50Hz)",
  "Kyrgyzstan":               "EU-compatible (Type C/F · 220V · 50Hz)",
  "Tajikistan":               "EU-compatible (Type C/F · 220V · 50Hz)",
  "Bangladesh":               "EU-compatible (Type C/D · 220V · 50Hz)",
  "Nepal":                    "EU-compatible (Type C/D · 230V · 50Hz)",
  "India":                    "EU-compatible (Type C/D/M · 230V · 50Hz) — Type M (large round 3-pin) most common",
  "Indonesia":                "EU-compatible (Type C/F · 230V · 50Hz)",

  // ── Asia mixed ────────────────────────────────────────────────────────────
  "Thailand":                 "Multi-type (Type A/B/C · 220V · 50Hz) — sockets usually accept US-style flat and EU-style round prongs",
  "Vietnam":                  "Multi-type (Type A/C/D · 220V · 50Hz) — modern outlets often accept US-style or EU-style prongs",
  "Cambodia":                 "Multi-type (Type A/C · 230V · 50Hz)",
  "Laos":                     "Multi-type (Type A/B/C · 230V · 50Hz)",
  "Myanmar":                  "Multi-type (Type C/D/G · 230V · 50Hz)",
};

// ─── Currency codes ───────────────────────────────────────────────────────────
// Used for real-time exchange rate lookups via the Frankfurter API.

export const CURRENCY_CODES: Record<string, string> = {
  "United States":        "USD",
  "United Kingdom":       "GBP",
  "European Union":       "EUR",
  "Australia":            "AUD",
  "Canada":               "CAD",
  "New Zealand":          "NZD",
  "Switzerland":          "CHF",
  "Norway":               "NOK",
  "Sweden":               "SEK",
  "Denmark":              "DKK",
  "Japan":                "JPY",
  "South Korea":          "KRW",
  "China":                "CNY",
  "Hong Kong":            "HKD",
  "Taiwan":               "TWD",
  "Singapore":            "SGD",
  "India":                "INR",
  "Thailand":             "THB",
  "Vietnam":              "VND",
  "Indonesia":            "IDR",
  "Philippines":          "PHP",
  "Malaysia":             "MYR",
  "Cambodia":             "KHR",
  "Myanmar":              "MMK",
  "Nepal":                "NPR",
  "Sri Lanka":            "LKR",
  "Bangladesh":           "BDT",
  "Pakistan":             "PKR",
  "Mongolia":             "MNT",
  "Kazakhstan":           "KZT",
  "Georgia":              "GEL",
  "Armenia":              "AMD",
  "Azerbaijan":           "AZN",
  "Uzbekistan":           "UZS",
  "Turkey":               "TRY",
  "Israel":               "ILS",
  "Jordan":               "JOD",
  "United Arab Emirates": "AED",
  "Qatar":                "QAR",
  "Saudi Arabia":         "SAR",
  "Kuwait":               "KWD",
  "Bahrain":              "BHD",
  "Egypt":                "EGP",
  "Morocco":              "MAD",
  "Tunisia":              "TND",
  "South Africa":         "ZAR",
  "Kenya":                "KES",
  "Tanzania":             "TZS",
  "Uganda":               "UGX",
  "Rwanda":               "RWF",
  "Ethiopia":             "ETB",
  "Ghana":                "GHS",
  "Nigeria":              "NGN",
  "Senegal":              "XOF",
  "France":               "EUR",
  "Germany":              "EUR",
  "Spain":                "EUR",
  "Italy":                "EUR",
  "Portugal":             "EUR",
  "Greece":               "EUR",
  "Netherlands":          "EUR",
  "Belgium":              "EUR",
  "Austria":              "EUR",
  "Finland":              "EUR",
  "Ireland":              "EUR",
  "Croatia":              "EUR",
  "Slovenia":             "EUR",
  "Slovakia":             "EUR",
  "Estonia":              "EUR",
  "Latvia":               "EUR",
  "Lithuania":            "EUR",
  "Malta":                "EUR",
  "Cyprus":               "EUR",
  "Poland":               "PLN",
  "Czech Republic":       "CZK",
  "Hungary":              "HUF",
  "Romania":              "RON",
  "Bulgaria":             "BGN",
  "Serbia":               "RSD",
  "Albania":              "ALL",
  "North Macedonia":      "MKD",
  "Bosnia and Herzegovina": "BAM",
  "Montenegro":           "EUR",
  "Ukraine":              "UAH",
  "Russia":               "RUB",
  "Mexico":               "MXN",
  "Colombia":             "COP",
  "Peru":                 "PEN",
  "Chile":                "CLP",
  "Argentina":            "ARS",
  "Brazil":               "BRL",
  "Bolivia":              "BOB",
  "Paraguay":             "PYG",
  "Uruguay":              "UYU",
  "Ecuador":              "USD",
  "Panama":               "USD",
  "Costa Rica":           "CRC",
  "Guatemala":            "GTQ",
  "Dominican Republic":   "DOP",
  "Cuba":                 "CUP",
  "Jamaica":              "JMD",
  "Trinidad and Tobago":  "TTD",
  "Iceland":              "ISK",
  "Maldives":             "MVR",
  "Laos":                 "LAK",
  "Brunei":               "BND",
};
