export type Continent = "Africa" | "Asia" | "Europe" | "North America" | "South America" | "Oceania";

export interface Country {
  alpha2: string;
  alpha3: string;
  numeric: string;  // ISO 3166-1 numeric — matches world-atlas geo IDs
  name: string;
  center: [number, number]; // [lng, lat]
  continent: Continent;
}

export const COUNTRIES: Country[] = [
  { alpha2: "AF", alpha3: "AFG", numeric: "004", name: "Afghanistan", center: [67.7, 33.9], continent: "Asia" },
  { alpha2: "AL", alpha3: "ALB", numeric: "008", name: "Albania", center: [20.2, 41.2], continent: "Europe" },
  { alpha2: "DZ", alpha3: "DZA", numeric: "012", name: "Algeria", center: [1.7, 28.0], continent: "Africa" },
  { alpha2: "AD", alpha3: "AND", numeric: "020", name: "Andorra", center: [1.6, 42.5], continent: "Europe" },
  { alpha2: "AO", alpha3: "AGO", numeric: "024", name: "Angola", center: [17.9, -11.2], continent: "Africa" },
  { alpha2: "AG", alpha3: "ATG", numeric: "028", name: "Antigua and Barbuda", center: [-61.8, 17.1], continent: "North America" },
  { alpha2: "AR", alpha3: "ARG", numeric: "032", name: "Argentina", center: [-63.6, -38.4], continent: "South America" },
  { alpha2: "AM", alpha3: "ARM", numeric: "051", name: "Armenia", center: [45.0, 40.1], continent: "Asia" },
  { alpha2: "AU", alpha3: "AUS", numeric: "036", name: "Australia", center: [133.8, -25.7], continent: "Oceania" },
  { alpha2: "AT", alpha3: "AUT", numeric: "040", name: "Austria", center: [14.6, 47.7], continent: "Europe" },
  { alpha2: "AZ", alpha3: "AZE", numeric: "031", name: "Azerbaijan", center: [47.6, 40.1], continent: "Asia" },
  { alpha2: "BS", alpha3: "BHS", numeric: "044", name: "Bahamas", center: [-77.4, 24.8], continent: "North America" },
  { alpha2: "BH", alpha3: "BHR", numeric: "048", name: "Bahrain", center: [50.6, 26.0], continent: "Asia" },
  { alpha2: "BD", alpha3: "BGD", numeric: "050", name: "Bangladesh", center: [90.4, 23.7], continent: "Asia" },
  { alpha2: "BB", alpha3: "BRB", numeric: "052", name: "Barbados", center: [-59.6, 13.2], continent: "North America" },
  { alpha2: "BY", alpha3: "BLR", numeric: "112", name: "Belarus", center: [28.0, 53.7], continent: "Europe" },
  { alpha2: "BE", alpha3: "BEL", numeric: "056", name: "Belgium", center: [4.5, 50.5], continent: "Europe" },
  { alpha2: "BZ", alpha3: "BLZ", numeric: "084", name: "Belize", center: [-88.5, 17.2], continent: "North America" },
  { alpha2: "BJ", alpha3: "BEN", numeric: "204", name: "Benin", center: [2.3, 9.3], continent: "Africa" },
  { alpha2: "BT", alpha3: "BTN", numeric: "064", name: "Bhutan", center: [90.4, 27.5], continent: "Asia" },
  { alpha2: "BO", alpha3: "BOL", numeric: "068", name: "Bolivia", center: [-64.7, -16.3], continent: "South America" },
  { alpha2: "BA", alpha3: "BIH", numeric: "070", name: "Bosnia and Herzegovina", center: [17.7, 44.2], continent: "Europe" },
  { alpha2: "BW", alpha3: "BWA", numeric: "072", name: "Botswana", center: [24.7, -22.3], continent: "Africa" },
  { alpha2: "BR", alpha3: "BRA", numeric: "076", name: "Brazil", center: [-51.9, -14.2], continent: "South America" },
  { alpha2: "BN", alpha3: "BRN", numeric: "096", name: "Brunei", center: [114.7, 4.5], continent: "Asia" },
  { alpha2: "BG", alpha3: "BGR", numeric: "100", name: "Bulgaria", center: [25.5, 42.7], continent: "Europe" },
  { alpha2: "BF", alpha3: "BFA", numeric: "854", name: "Burkina Faso", center: [-1.6, 12.4], continent: "Africa" },
  { alpha2: "BI", alpha3: "BDI", numeric: "108", name: "Burundi", center: [29.9, -3.4], continent: "Africa" },
  { alpha2: "CV", alpha3: "CPV", numeric: "132", name: "Cabo Verde", center: [-24.0, 16.0], continent: "Africa" },
  { alpha2: "KH", alpha3: "KHM", numeric: "116", name: "Cambodia", center: [104.9, 12.6], continent: "Asia" },
  { alpha2: "CM", alpha3: "CMR", numeric: "120", name: "Cameroon", center: [12.4, 5.7], continent: "Africa" },
  { alpha2: "CA", alpha3: "CAN", numeric: "124", name: "Canada", center: [-96.8, 56.1], continent: "North America" },
  { alpha2: "CF", alpha3: "CAF", numeric: "140", name: "Central African Republic", center: [20.9, 6.6], continent: "Africa" },
  { alpha2: "TD", alpha3: "TCD", numeric: "148", name: "Chad", center: [18.7, 15.5], continent: "Africa" },
  { alpha2: "CL", alpha3: "CHL", numeric: "152", name: "Chile", center: [-71.5, -35.7], continent: "South America" },
  { alpha2: "CN", alpha3: "CHN", numeric: "156", name: "China", center: [104.2, 35.9], continent: "Asia" },
  { alpha2: "CO", alpha3: "COL", numeric: "170", name: "Colombia", center: [-74.3, 4.6], continent: "South America" },
  { alpha2: "KM", alpha3: "COM", numeric: "174", name: "Comoros", center: [43.9, -12.0], continent: "Africa" },
  { alpha2: "CG", alpha3: "COG", numeric: "178", name: "Congo", center: [15.8, -0.2], continent: "Africa" },
  { alpha2: "CD", alpha3: "COD", numeric: "180", name: "Congo (DRC)", center: [24.0, -2.9], continent: "Africa" },
  { alpha2: "CR", alpha3: "CRI", numeric: "188", name: "Costa Rica", center: [-84.0, 9.7], continent: "North America" },
  { alpha2: "HR", alpha3: "HRV", numeric: "191", name: "Croatia", center: [15.2, 45.1], continent: "Europe" },
  { alpha2: "CU", alpha3: "CUB", numeric: "192", name: "Cuba", center: [-79.5, 21.5], continent: "North America" },
  { alpha2: "CY", alpha3: "CYP", numeric: "196", name: "Cyprus", center: [33.4, 35.1], continent: "Asia" },
  { alpha2: "CZ", alpha3: "CZE", numeric: "203", name: "Czech Republic", center: [15.5, 49.8], continent: "Europe" },
  { alpha2: "DK", alpha3: "DNK", numeric: "208", name: "Denmark", center: [9.5, 56.3], continent: "Europe" },
  { alpha2: "DJ", alpha3: "DJI", numeric: "262", name: "Djibouti", center: [42.6, 11.8], continent: "Africa" },
  { alpha2: "DM", alpha3: "DMA", numeric: "212", name: "Dominica", center: [-61.4, 15.4], continent: "North America" },
  { alpha2: "DO", alpha3: "DOM", numeric: "214", name: "Dominican Republic", center: [-70.2, 18.7], continent: "North America" },
  { alpha2: "EC", alpha3: "ECU", numeric: "218", name: "Ecuador", center: [-78.2, -1.8], continent: "South America" },
  { alpha2: "EG", alpha3: "EGY", numeric: "818", name: "Egypt", center: [30.8, 26.8], continent: "Africa" },
  { alpha2: "SV", alpha3: "SLV", numeric: "222", name: "El Salvador", center: [-88.9, 13.8], continent: "North America" },
  { alpha2: "GQ", alpha3: "GNQ", numeric: "226", name: "Equatorial Guinea", center: [10.3, 1.7], continent: "Africa" },
  { alpha2: "ER", alpha3: "ERI", numeric: "232", name: "Eritrea", center: [38.9, 15.2], continent: "Africa" },
  { alpha2: "EE", alpha3: "EST", numeric: "233", name: "Estonia", center: [25.0, 58.6], continent: "Europe" },
  { alpha2: "SZ", alpha3: "SWZ", numeric: "748", name: "Eswatini", center: [31.5, -26.5], continent: "Africa" },
  { alpha2: "ET", alpha3: "ETH", numeric: "231", name: "Ethiopia", center: [40.5, 9.1], continent: "Africa" },
  { alpha2: "FJ", alpha3: "FJI", numeric: "242", name: "Fiji", center: [178.1, -17.7], continent: "Oceania" },
  { alpha2: "FI", alpha3: "FIN", numeric: "246", name: "Finland", center: [26.3, 64.0], continent: "Europe" },
  { alpha2: "FR", alpha3: "FRA", numeric: "250", name: "France", center: [2.2, 46.2], continent: "Europe" },
  { alpha2: "GA", alpha3: "GAB", numeric: "266", name: "Gabon", center: [11.6, -0.8], continent: "Africa" },
  { alpha2: "GM", alpha3: "GMB", numeric: "270", name: "Gambia", center: [-15.3, 13.5], continent: "Africa" },
  { alpha2: "GE", alpha3: "GEO", numeric: "268", name: "Georgia", center: [43.4, 42.3], continent: "Asia" },
  { alpha2: "DE", alpha3: "DEU", numeric: "276", name: "Germany", center: [10.5, 51.2], continent: "Europe" },
  { alpha2: "GH", alpha3: "GHA", numeric: "288", name: "Ghana", center: [-1.0, 7.9], continent: "Africa" },
  { alpha2: "GR", alpha3: "GRC", numeric: "300", name: "Greece", center: [21.8, 39.1], continent: "Europe" },
  { alpha2: "GD", alpha3: "GRD", numeric: "308", name: "Grenada", center: [-61.7, 12.1], continent: "North America" },
  { alpha2: "GT", alpha3: "GTM", numeric: "320", name: "Guatemala", center: [-90.2, 15.8], continent: "North America" },
  { alpha2: "GN", alpha3: "GIN", numeric: "324", name: "Guinea", center: [-11.8, 10.9], continent: "Africa" },
  { alpha2: "GW", alpha3: "GNB", numeric: "624", name: "Guinea-Bissau", center: [-15.2, 11.8], continent: "Africa" },
  { alpha2: "GY", alpha3: "GUY", numeric: "328", name: "Guyana", center: [-59.0, 5.0], continent: "South America" },
  { alpha2: "HT", alpha3: "HTI", numeric: "332", name: "Haiti", center: [-72.3, 19.0], continent: "North America" },
  { alpha2: "HN", alpha3: "HND", numeric: "340", name: "Honduras", center: [-86.6, 15.2], continent: "North America" },
  { alpha2: "HU", alpha3: "HUN", numeric: "348", name: "Hungary", center: [19.5, 47.2], continent: "Europe" },
  { alpha2: "IS", alpha3: "ISL", numeric: "352", name: "Iceland", center: [-18.5, 65.0], continent: "Europe" },
  { alpha2: "IN", alpha3: "IND", numeric: "356", name: "India", center: [79.0, 22.5], continent: "Asia" },
  { alpha2: "ID", alpha3: "IDN", numeric: "360", name: "Indonesia", center: [117.7, -0.8], continent: "Asia" },
  { alpha2: "IR", alpha3: "IRN", numeric: "364", name: "Iran", center: [53.7, 32.4], continent: "Asia" },
  { alpha2: "IQ", alpha3: "IRQ", numeric: "368", name: "Iraq", center: [43.7, 33.2], continent: "Asia" },
  { alpha2: "IE", alpha3: "IRL", numeric: "372", name: "Ireland", center: [-8.2, 53.4], continent: "Europe" },
  { alpha2: "IL", alpha3: "ISR", numeric: "376", name: "Israel", center: [34.9, 31.5], continent: "Asia" },
  { alpha2: "IT", alpha3: "ITA", numeric: "380", name: "Italy", center: [12.6, 42.5], continent: "Europe" },
  { alpha2: "JM", alpha3: "JAM", numeric: "388", name: "Jamaica", center: [-77.3, 18.1], continent: "North America" },
  { alpha2: "JP", alpha3: "JPN", numeric: "392", name: "Japan", center: [138.3, 36.2], continent: "Asia" },
  { alpha2: "JO", alpha3: "JOR", numeric: "400", name: "Jordan", center: [36.2, 30.6], continent: "Asia" },
  { alpha2: "KZ", alpha3: "KAZ", numeric: "398", name: "Kazakhstan", center: [67.0, 48.0], continent: "Asia" },
  { alpha2: "KE", alpha3: "KEN", numeric: "404", name: "Kenya", center: [37.9, 0.0], continent: "Africa" },
  { alpha2: "KI", alpha3: "KIR", numeric: "296", name: "Kiribati", center: [-157.4, 1.9], continent: "Oceania" },
  { alpha2: "KW", alpha3: "KWT", numeric: "414", name: "Kuwait", center: [47.5, 29.5], continent: "Asia" },
  { alpha2: "KG", alpha3: "KGZ", numeric: "417", name: "Kyrgyzstan", center: [74.6, 41.2], continent: "Asia" },
  { alpha2: "KP", alpha3: "PRK", numeric: "408", name: "North Korea", center: [127.5, 40.3], continent: "Asia" },
  { alpha2: "KR", alpha3: "KOR", numeric: "410", name: "South Korea", center: [127.8, 36.5], continent: "Asia" },
  { alpha2: "CI", alpha3: "CIV", numeric: "384", name: "Côte d'Ivoire", center: [-5.5, 7.5], continent: "Africa" },
  { alpha2: "PS", alpha3: "PSE", numeric: "275", name: "Palestine", center: [35.2, 31.9], continent: "Asia" },
  { alpha2: "XK", alpha3: "XKX", numeric: "383", name: "Kosovo", center: [20.9, 42.6], continent: "Europe" },
  { alpha2: "CW", alpha3: "CUW", numeric: "531", name: "Curaçao", center: [-68.9, 12.2], continent: "North America" },
  { alpha2: "SX", alpha3: "SXM", numeric: "534", name: "Sint Maarten", center: [-63.1, 18.0], continent: "North America" },
  { alpha2: "LA", alpha3: "LAO", numeric: "418", name: "Laos", center: [103.8, 18.2], continent: "Asia" },
  { alpha2: "LV", alpha3: "LVA", numeric: "428", name: "Latvia", center: [24.6, 56.9], continent: "Europe" },
  { alpha2: "LB", alpha3: "LBN", numeric: "422", name: "Lebanon", center: [35.9, 33.9], continent: "Asia" },
  { alpha2: "LS", alpha3: "LSO", numeric: "426", name: "Lesotho", center: [28.2, -29.6], continent: "Africa" },
  { alpha2: "LR", alpha3: "LBR", numeric: "430", name: "Liberia", center: [-9.4, 6.4], continent: "Africa" },
  { alpha2: "LY", alpha3: "LBY", numeric: "434", name: "Libya", center: [17.2, 26.3], continent: "Africa" },
  { alpha2: "LI", alpha3: "LIE", numeric: "438", name: "Liechtenstein", center: [9.6, 47.1], continent: "Europe" },
  { alpha2: "LT", alpha3: "LTU", numeric: "440", name: "Lithuania", center: [23.9, 55.2], continent: "Europe" },
  { alpha2: "LU", alpha3: "LUX", numeric: "442", name: "Luxembourg", center: [6.1, 49.8], continent: "Europe" },
  { alpha2: "MG", alpha3: "MDG", numeric: "450", name: "Madagascar", center: [46.9, -18.8], continent: "Africa" },
  { alpha2: "MW", alpha3: "MWI", numeric: "454", name: "Malawi", center: [34.3, -13.3], continent: "Africa" },
  { alpha2: "MY", alpha3: "MYS", numeric: "458", name: "Malaysia", center: [109.7, 4.2], continent: "Asia" },
  { alpha2: "MV", alpha3: "MDV", numeric: "462", name: "Maldives", center: [73.5, 3.2], continent: "Asia" },
  { alpha2: "ML", alpha3: "MLI", numeric: "466", name: "Mali", center: [-2.0, 17.6], continent: "Africa" },
  { alpha2: "MT", alpha3: "MLT", numeric: "470", name: "Malta", center: [14.4, 35.9], continent: "Europe" },
  { alpha2: "MH", alpha3: "MHL", numeric: "584", name: "Marshall Islands", center: [168.7, 7.1], continent: "Oceania" },
  { alpha2: "MR", alpha3: "MRT", numeric: "478", name: "Mauritania", center: [-10.9, 21.0], continent: "Africa" },
  { alpha2: "MU", alpha3: "MUS", numeric: "480", name: "Mauritius", center: [57.6, -20.3], continent: "Africa" },
  { alpha2: "MX", alpha3: "MEX", numeric: "484", name: "Mexico", center: [-102.5, 24.0], continent: "North America" },
  { alpha2: "FM", alpha3: "FSM", numeric: "583", name: "Micronesia", center: [158.2, 6.9], continent: "Oceania" },
  { alpha2: "MD", alpha3: "MDA", numeric: "498", name: "Moldova", center: [28.4, 47.4], continent: "Europe" },
  { alpha2: "MC", alpha3: "MCO", numeric: "492", name: "Monaco", center: [7.4, 43.7], continent: "Europe" },
  { alpha2: "MN", alpha3: "MNG", numeric: "496", name: "Mongolia", center: [103.8, 46.9], continent: "Asia" },
  { alpha2: "ME", alpha3: "MNE", numeric: "499", name: "Montenegro", center: [19.4, 42.7], continent: "Europe" },
  { alpha2: "MA", alpha3: "MAR", numeric: "504", name: "Morocco", center: [-7.1, 31.8], continent: "Africa" },
  { alpha2: "MZ", alpha3: "MOZ", numeric: "508", name: "Mozambique", center: [35.6, -18.7], continent: "Africa" },
  { alpha2: "MM", alpha3: "MMR", numeric: "104", name: "Myanmar", center: [96.7, 19.2], continent: "Asia" },
  { alpha2: "NA", alpha3: "NAM", numeric: "516", name: "Namibia", center: [18.5, -22.0], continent: "Africa" },
  { alpha2: "NR", alpha3: "NRU", numeric: "520", name: "Nauru", center: [166.9, -0.5], continent: "Oceania" },
  { alpha2: "NP", alpha3: "NPL", numeric: "524", name: "Nepal", center: [84.1, 28.4], continent: "Asia" },
  { alpha2: "NL", alpha3: "NLD", numeric: "528", name: "Netherlands", center: [5.3, 52.1], continent: "Europe" },
  { alpha2: "NZ", alpha3: "NZL", numeric: "554", name: "New Zealand", center: [172.5, -42.3], continent: "Oceania" },
  { alpha2: "NI", alpha3: "NIC", numeric: "558", name: "Nicaragua", center: [-85.2, 12.9], continent: "North America" },
  { alpha2: "NE", alpha3: "NER", numeric: "562", name: "Niger", center: [8.1, 17.6], continent: "Africa" },
  { alpha2: "NG", alpha3: "NGA", numeric: "566", name: "Nigeria", center: [8.7, 9.1], continent: "Africa" },
  { alpha2: "MK", alpha3: "MKD", numeric: "807", name: "North Macedonia", center: [21.7, 41.6], continent: "Europe" },
  { alpha2: "NO", alpha3: "NOR", numeric: "578", name: "Norway", center: [8.5, 60.5], continent: "Europe" },
  { alpha2: "OM", alpha3: "OMN", numeric: "512", name: "Oman", center: [57.6, 21.5], continent: "Asia" },
  { alpha2: "PK", alpha3: "PAK", numeric: "586", name: "Pakistan", center: [69.3, 30.4], continent: "Asia" },
  { alpha2: "PW", alpha3: "PLW", numeric: "585", name: "Palau", center: [134.6, 7.5], continent: "Oceania" },
  { alpha2: "PA", alpha3: "PAN", numeric: "591", name: "Panama", center: [-80.8, 8.5], continent: "North America" },
  { alpha2: "PG", alpha3: "PNG", numeric: "598", name: "Papua New Guinea", center: [143.9, -6.3], continent: "Oceania" },
  { alpha2: "PY", alpha3: "PRY", numeric: "600", name: "Paraguay", center: [-58.4, -23.4], continent: "South America" },
  { alpha2: "PE", alpha3: "PER", numeric: "604", name: "Peru", center: [-75.0, -9.2], continent: "South America" },
  { alpha2: "PH", alpha3: "PHL", numeric: "608", name: "Philippines", center: [122.9, 12.9], continent: "Asia" },
  { alpha2: "PL", alpha3: "POL", numeric: "616", name: "Poland", center: [19.1, 52.1], continent: "Europe" },
  { alpha2: "PT", alpha3: "PRT", numeric: "620", name: "Portugal", center: [-8.2, 39.4], continent: "Europe" },
  { alpha2: "QA", alpha3: "QAT", numeric: "634", name: "Qatar", center: [51.2, 25.4], continent: "Asia" },
  { alpha2: "RO", alpha3: "ROU", numeric: "642", name: "Romania", center: [25.0, 45.9], continent: "Europe" },
  { alpha2: "RU", alpha3: "RUS", numeric: "643", name: "Russia", center: [105.3, 61.5], continent: "Europe" },
  { alpha2: "RW", alpha3: "RWA", numeric: "646", name: "Rwanda", center: [29.9, -1.9], continent: "Africa" },
  { alpha2: "KN", alpha3: "KNA", numeric: "659", name: "Saint Kitts and Nevis", center: [-62.8, 17.3], continent: "North America" },
  { alpha2: "LC", alpha3: "LCA", numeric: "662", name: "Saint Lucia", center: [-60.9, 13.9], continent: "North America" },
  { alpha2: "VC", alpha3: "VCT", numeric: "670", name: "Saint Vincent and the Grenadines", center: [-61.2, 13.3], continent: "North America" },
  { alpha2: "WS", alpha3: "WSM", numeric: "882", name: "Samoa", center: [-172.5, -13.8], continent: "Oceania" },
  { alpha2: "SM", alpha3: "SMR", numeric: "674", name: "San Marino", center: [12.5, 43.9], continent: "Europe" },
  { alpha2: "ST", alpha3: "STP", numeric: "678", name: "Sao Tome and Principe", center: [6.6, 0.2], continent: "Africa" },
  { alpha2: "SA", alpha3: "SAU", numeric: "682", name: "Saudi Arabia", center: [45.1, 24.2], continent: "Asia" },
  { alpha2: "SN", alpha3: "SEN", numeric: "686", name: "Senegal", center: [-14.5, 14.5], continent: "Africa" },
  { alpha2: "RS", alpha3: "SRB", numeric: "688", name: "Serbia", center: [21.0, 44.0], continent: "Europe" },
  { alpha2: "SC", alpha3: "SYC", numeric: "690", name: "Seychelles", center: [55.5, -4.7], continent: "Africa" },
  { alpha2: "SL", alpha3: "SLE", numeric: "694", name: "Sierra Leone", center: [-11.8, 8.5], continent: "Africa" },
  { alpha2: "SG", alpha3: "SGP", numeric: "702", name: "Singapore", center: [103.8, 1.4], continent: "Asia" },
  { alpha2: "SK", alpha3: "SVK", numeric: "703", name: "Slovakia", center: [19.7, 48.7], continent: "Europe" },
  { alpha2: "SI", alpha3: "SVN", numeric: "705", name: "Slovenia", center: [14.8, 46.1], continent: "Europe" },
  { alpha2: "SB", alpha3: "SLB", numeric: "090", name: "Solomon Islands", center: [160.2, -9.6], continent: "Oceania" },
  { alpha2: "SO", alpha3: "SOM", numeric: "706", name: "Somalia", center: [46.2, 5.2], continent: "Africa" },
  { alpha2: "ZA", alpha3: "ZAF", numeric: "710", name: "South Africa", center: [25.1, -29.0], continent: "Africa" },
  { alpha2: "SS", alpha3: "SSD", numeric: "728", name: "South Sudan", center: [31.3, 7.9], continent: "Africa" },
  { alpha2: "ES", alpha3: "ESP", numeric: "724", name: "Spain", center: [-3.7, 40.2], continent: "Europe" },
  { alpha2: "LK", alpha3: "LKA", numeric: "144", name: "Sri Lanka", center: [80.7, 7.9], continent: "Asia" },
  { alpha2: "SD", alpha3: "SDN", numeric: "729", name: "Sudan", center: [29.9, 12.9], continent: "Africa" },
  { alpha2: "SR", alpha3: "SUR", numeric: "740", name: "Suriname", center: [-56.0, 4.1], continent: "South America" },
  { alpha2: "SE", alpha3: "SWE", numeric: "752", name: "Sweden", center: [18.6, 60.1], continent: "Europe" },
  { alpha2: "CH", alpha3: "CHE", numeric: "756", name: "Switzerland", center: [8.2, 46.8], continent: "Europe" },
  { alpha2: "SY", alpha3: "SYR", numeric: "760", name: "Syria", center: [38.5, 35.0], continent: "Asia" },
  { alpha2: "TW", alpha3: "TWN", numeric: "158", name: "Taiwan", center: [120.9, 23.7], continent: "Asia" },
  { alpha2: "TJ", alpha3: "TJK", numeric: "762", name: "Tajikistan", center: [71.3, 38.9], continent: "Asia" },
  { alpha2: "TZ", alpha3: "TZA", numeric: "834", name: "Tanzania", center: [34.9, -6.4], continent: "Africa" },
  { alpha2: "TH", alpha3: "THA", numeric: "764", name: "Thailand", center: [101.0, 15.9], continent: "Asia" },
  { alpha2: "TL", alpha3: "TLS", numeric: "626", name: "Timor-Leste", center: [125.7, -8.9], continent: "Asia" },
  { alpha2: "TG", alpha3: "TGO", numeric: "768", name: "Togo", center: [0.8, 8.6], continent: "Africa" },
  { alpha2: "TO", alpha3: "TON", numeric: "776", name: "Tonga", center: [-175.2, -21.2], continent: "Oceania" },
  { alpha2: "TT", alpha3: "TTO", numeric: "780", name: "Trinidad and Tobago", center: [-61.2, 10.7], continent: "North America" },
  { alpha2: "TN", alpha3: "TUN", numeric: "788", name: "Tunisia", center: [9.6, 33.9], continent: "Africa" },
  { alpha2: "TR", alpha3: "TUR", numeric: "792", name: "Turkey", center: [35.2, 38.9], continent: "Asia" },
  { alpha2: "TM", alpha3: "TKM", numeric: "795", name: "Turkmenistan", center: [58.4, 39.6], continent: "Asia" },
  { alpha2: "TV", alpha3: "TUV", numeric: "798", name: "Tuvalu", center: [177.1, -7.5], continent: "Oceania" },
  { alpha2: "UG", alpha3: "UGA", numeric: "800", name: "Uganda", center: [32.3, 1.4], continent: "Africa" },
  { alpha2: "UA", alpha3: "UKR", numeric: "804", name: "Ukraine", center: [31.2, 48.4], continent: "Europe" },
  { alpha2: "AE", alpha3: "ARE", numeric: "784", name: "United Arab Emirates", center: [53.8, 24.0], continent: "Asia" },
  { alpha2: "GB", alpha3: "GBR", numeric: "826", name: "United Kingdom", center: [-3.4, 55.4], continent: "Europe" },
  { alpha2: "US", alpha3: "USA", numeric: "840", name: "United States", center: [-98.6, 39.8], continent: "North America" },
  { alpha2: "UY", alpha3: "URY", numeric: "858", name: "Uruguay", center: [-55.8, -32.5], continent: "South America" },
  { alpha2: "UZ", alpha3: "UZB", numeric: "860", name: "Uzbekistan", center: [63.9, 41.4], continent: "Asia" },
  { alpha2: "VU", alpha3: "VUT", numeric: "548", name: "Vanuatu", center: [166.9, -15.4], continent: "Oceania" },
  { alpha2: "VE", alpha3: "VEN", numeric: "862", name: "Venezuela", center: [-66.6, 8.0], continent: "South America" },
  { alpha2: "VN", alpha3: "VNM", numeric: "704", name: "Vietnam", center: [108.3, 14.1], continent: "Asia" },
  { alpha2: "YE", alpha3: "YEM", numeric: "887", name: "Yemen", center: [48.5, 15.6], continent: "Asia" },
  { alpha2: "ZM", alpha3: "ZMB", numeric: "894", name: "Zambia", center: [27.8, -13.1], continent: "Africa" },
  { alpha2: "ZW", alpha3: "ZWE", numeric: "716", name: "Zimbabwe", center: [29.9, -19.0], continent: "Africa" },
];

// Lookup maps
export const byAlpha2 = Object.fromEntries(COUNTRIES.map((c) => [c.alpha2, c]));
export const byNumeric = Object.fromEntries(COUNTRIES.map((c) => [c.numeric, c]));

// Use the raw numeric string (no parseInt) to match world-atlas geo IDs exactly
export const numericToAlpha2: Record<string, string> = {};
for (const c of COUNTRIES) {
  // world-atlas stores IDs as numbers; toString() on e.g. 4 gives "4", but our numeric is "004"
  // so we index by both the zero-padded form and the int-parsed form
  numericToAlpha2[c.numeric] = c.alpha2;
  numericToAlpha2[String(parseInt(c.numeric, 10))] = c.alpha2;
}

export const SORTED_COUNTRIES = [...COUNTRIES].sort((a, b) =>
  a.name.localeCompare(b.name)
);

export const ALL_CONTINENTS: Continent[] = [
  "Africa", "Asia", "Europe", "North America", "Oceania", "South America",
];
