/**
 * Lookup map of IATA airport code → primary city served.
 * Covers the most common international and domestic airports.
 */
export const IATA_CITY: Record<string, string> = {
  // Asia-Pacific
  BKK: "Bangkok", DMK: "Bangkok", CNX: "Chiang Mai", HKT: "Phuket", USM: "Koh Samui",
  KBV: "Krabi", CEI: "Chiang Rai",
  SGN: "Ho Chi Minh City", HAN: "Hanoi", DAD: "Da Nang", VCA: "Can Tho", HPH: "Haiphong",
  KUL: "Kuala Lumpur", PEN: "Penang", LGK: "Langkawi", BKI: "Kota Kinabalu", KCH: "Kuching",
  SIN: "Singapore",
  CGK: "Jakarta", DPS: "Bali", SUB: "Surabaya", UPG: "Makassar", LOP: "Lombok",
  MNL: "Manila", CEB: "Cebu", CRK: "Clark", DVO: "Davao", ILO: "Iloilo",
  BNE: "Brisbane", SYD: "Sydney", MEL: "Melbourne", PER: "Perth", ADL: "Adelaide",
  CBR: "Canberra", OOL: "Gold Coast", CNS: "Cairns", DRW: "Darwin", HBA: "Hobart",
  AKL: "Auckland", CHC: "Christchurch", WLG: "Wellington", ZQN: "Queenstown",
  NAN: "Nadi",
  HKG: "Hong Kong",
  TPE: "Taipei", KHH: "Kaohsiung", RMQ: "Taichung",
  PEK: "Beijing", PKX: "Beijing", PVG: "Shanghai", SHA: "Shanghai",
  CAN: "Guangzhou", SZX: "Shenzhen", CTU: "Chengdu", CKG: "Chongqing",
  XIY: "Xi'an", KMG: "Kunming", HGH: "Hangzhou", NKG: "Nanjing", WUH: "Wuhan",
  TFU: "Chengdu",
  NRT: "Tokyo", HND: "Tokyo", KIX: "Osaka", ITM: "Osaka", NGO: "Nagoya",
  CTS: "Sapporo", OKA: "Okinawa", FUK: "Fukuoka", HIJ: "Hiroshima",
  ICN: "Seoul", GMP: "Seoul", PUS: "Busan", CJU: "Jeju",
  RGN: "Yangon", MDL: "Mandalay",
  DAC: "Dhaka", CGP: "Chittagong",
  CMB: "Colombo",
  KTM: "Kathmandu",
  DEL: "Delhi", BOM: "Mumbai", BLR: "Bangalore", MAA: "Chennai", CCU: "Kolkata",
  HYD: "Hyderabad", AMD: "Ahmedabad", PNQ: "Pune", GOI: "Goa", COK: "Kochi",
  TRV: "Trivandrum", IXC: "Chandigarh", LKO: "Lucknow", PAT: "Patna",
  MLE: "Male",
  VTE: "Vientiane", LPQ: "Luang Prabang",
  PNH: "Phnom Penh", REP: "Siem Reap",
  KHI: "Karachi", LHE: "Lahore", ISB: "Islamabad",
  TAS: "Tashkent", ALA: "Almaty",
  ULN: "Ulaanbaatar",

  // Middle East
  DXB: "Dubai", AUH: "Abu Dhabi", SHJ: "Sharjah", RKT: "Ras Al Khaimah",
  DOH: "Doha", BAH: "Bahrain", KWI: "Kuwait City",
  AMM: "Amman", BEY: "Beirut", DAM: "Damascus",
  TLV: "Tel Aviv",
  MCT: "Muscat",
  RUH: "Riyadh", JED: "Jeddah", DMM: "Dammam",
  THR: "Tehran", IKA: "Tehran", MHD: "Mashhad",

  // Europe
  LHR: "London", LGW: "London", STN: "London", LTN: "London", LCY: "London",
  CDG: "Paris", ORY: "Paris", BVA: "Paris",
  AMS: "Amsterdam",
  FRA: "Frankfurt", MUC: "Munich", TXL: "Berlin", BER: "Berlin", DUS: "Düsseldorf",
  HAM: "Hamburg", STR: "Stuttgart", CGN: "Cologne", NUE: "Nuremberg",
  ZRH: "Zurich", GVA: "Geneva", BSL: "Basel",
  VIE: "Vienna",
  BRU: "Brussels",
  MAD: "Madrid", BCN: "Barcelona", AGP: "Malaga", PMI: "Palma", SVQ: "Seville",
  VLC: "Valencia", BIO: "Bilbao", ALC: "Alicante", IBZ: "Ibiza",
  LIS: "Lisbon", OPO: "Porto", FAO: "Faro",
  FCO: "Rome", MXP: "Milan", LIN: "Milan", VCE: "Venice", NAP: "Naples",
  CTA: "Catania", PMO: "Palermo", BRI: "Bari", FLR: "Florence",
  ATH: "Athens", SKG: "Thessaloniki", HER: "Heraklion", RHO: "Rhodes",
  IST: "Istanbul", SAW: "Istanbul", AYT: "Antalya", ESB: "Ankara", ADB: "Izmir",
  SVO: "Moscow", DME: "Moscow", VKO: "Moscow", LED: "St Petersburg",
  WAW: "Warsaw", KRK: "Krakow",
  PRG: "Prague",
  BUD: "Budapest",
  BUH: "Bucharest", OTP: "Bucharest",
  SOF: "Sofia",
  ZAG: "Zagreb", SPU: "Split", DBV: "Dubrovnik",
  BEG: "Belgrade",
  LJU: "Ljubljana",
  TIA: "Tirana",
  SKP: "Skopje",
  SJJ: "Sarajevo",
  OHD: "Ohrid", MKD: "Skopje",
  CPH: "Copenhagen",
  ARN: "Stockholm", GOT: "Gothenburg", MMX: "Malmö",
  OSL: "Oslo", BGO: "Bergen", TRF: "Oslo",
  HEL: "Helsinki",
  RVN: "Rovaniemi",
  KEF: "Reykjavik",
  DUB: "Dublin", SNN: "Shannon", ORK: "Cork",
  EDI: "Edinburgh", GLA: "Glasgow", BHX: "Birmingham", MAN: "Manchester",
  BRS: "Bristol", NCL: "Newcastle",
  CIA: "Rome",
  TLL: "Tallinn", RIX: "Riga", VNO: "Vilnius",
  MSQ: "Minsk",
  KBP: "Kyiv", IEV: "Kyiv", LWO: "Lviv",
  GYD: "Baku",
  TBS: "Tbilisi",
  EVN: "Yerevan",

  // Africa
  CAI: "Cairo", LXR: "Luxor", HRG: "Hurghada", SSH: "Sharm el-Sheikh",
  CMN: "Casablanca", RAK: "Marrakech", FEZ: "Fez", TNG: "Tangier",
  ALG: "Algiers",
  TUN: "Tunis",
  TRP: "Tripoli",
  ADD: "Addis Ababa",
  NBO: "Nairobi", MBA: "Mombasa",
  DAR: "Dar es Salaam", JRO: "Kilimanjaro", ZNZ: "Zanzibar",
  EBB: "Entebbe",
  KGL: "Kigali",
  ACC: "Accra",
  LOS: "Lagos", ABV: "Abuja", KAN: "Kano",
  JNB: "Johannesburg", CPT: "Cape Town", DUR: "Durban",
  WDH: "Windhoek",
  GBE: "Gaborone",
  HRE: "Harare",
  MPM: "Maputo",
  MRU: "Mauritius",
  SEZ: "Seychelles",
  TNR: "Antananarivo",
  ROB: "Monrovia",
  ABJ: "Abidjan",
  DKR: "Dakar",

  // Americas
  JFK: "New York", LGA: "New York", EWR: "New York",
  LAX: "Los Angeles", SFO: "San Francisco", SJC: "San Jose",
  ORD: "Chicago", MDW: "Chicago",
  ATL: "Atlanta",
  DFW: "Dallas", DAL: "Dallas",
  MIA: "Miami", FLL: "Fort Lauderdale",
  SEA: "Seattle",
  BOS: "Boston",
  DEN: "Denver",
  LAS: "Las Vegas",
  PHX: "Phoenix",
  MSP: "Minneapolis",
  DTW: "Detroit",
  IAH: "Houston", HOU: "Houston",
  PHL: "Philadelphia",
  CLT: "Charlotte",
  DCA: "Washington", IAD: "Washington", BWI: "Baltimore",
  SAN: "San Diego",
  TPA: "Tampa",
  PDX: "Portland",
  SLC: "Salt Lake City",
  AUS: "Austin",
  MCO: "Orlando",
  BNA: "Nashville",
  RDU: "Raleigh",
  STL: "St Louis",
  MCI: "Kansas City",
  MKE: "Milwaukee",
  YYZ: "Toronto", YYC: "Calgary", YVR: "Vancouver", YUL: "Montreal",
  YEG: "Edmonton", YOW: "Ottawa", YHZ: "Halifax",
  GRU: "São Paulo", CGH: "São Paulo", VCP: "Campinas",
  GIG: "Rio de Janeiro", SDU: "Rio de Janeiro",
  BSB: "Brasília", SSA: "Salvador", FOR: "Fortaleza", REC: "Recife",
  MVD: "Montevideo",
  EZE: "Buenos Aires", AEP: "Buenos Aires",
  SCL: "Santiago",
  LIM: "Lima",
  BOG: "Bogotá", MDE: "Medellín", CLO: "Cali", CTG: "Cartagena",
  GYE: "Guayaquil", UIO: "Quito",
  CCS: "Caracas",
  PTY: "Panama City",
  SJO: "San José", LIR: "Liberia",
  GUA: "Guatemala City",
  SAL: "San Salvador",
  MGA: "Managua",
  TGU: "Tegucigalpa", RTB: "Roatán",
  HAV: "Havana",
  SDQ: "Santo Domingo", PUJ: "Punta Cana",
  SJU: "San Juan",
  MBJ: "Montego Bay", KIN: "Kingston",
  MEX: "Mexico City", CUN: "Cancún", GDL: "Guadalajara",
  MTY: "Monterrey", PVR: "Puerto Vallarta", SJD: "Los Cabos",
  OAX: "Oaxaca", MID: "Mérida",

  // Central Asia & Caucasus
  AKX: "Aktobe", CIT: "Shymkent", URA: "Oral",
  FRU: "Bishkek", OSS: "Osh",
  DYU: "Dushanbe",
  ASB: "Ashgabat",
};

/**
 * Returns the city name for a given IATA code, or null if not found.
 */
export function cityFromIata(iata: string): string | null {
  return IATA_CITY[iata.toUpperCase().trim()] ?? null;
}
